---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: vlanstatuses.network.harvesterhci.io
spec:
  group: network.harvesterhci.io
  names:
    kind: VlanStatus
    listKind: VlanStatusList
    plural: vlanstatuses
    shortNames:
    - vs
    - vss
    singular: vlanstatus
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.clusterNetwork
      name: CLUSTERNETWORK
      type: string
    - jsonPath: .status.vlanConfig
      name: VLANCONFIG
      type: string
    - jsonPath: .status.node
      name: NODE
      type: string
    - jsonPath: .spec.description
      name: DESCRIPTION
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          status:
            properties:
              clusterNetwork:
                type: string
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              linkMonitor:
                type: string
              localAreas:
                items:
                  properties:
                    cidr:
                      type: string
                    vlanID:
                      type: integer
                  required:
                  - vlanID
                  type: object
                type: array
              node:
                type: string
              vlanConfig:
                type: string
            required:
            - clusterNetwork
            - linkMonitor
            - node
            - vlanConfig
            type: object
        required:
        - status
        type: object
    served: true
    storage: true
    subresources: {}
