#!/bin/bash
set -e

source $(dirname $0)/version

SUFFIX="-${ARCH}"

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

mkdir -p dist/artifacts
cp bin/harvester-network-controller${SUFFIX} dist/artifacts/harvester-network-controller${SUFFIX}
cp bin/harvester-network-helper${SUFFIX} dist/artifacts/harvester-network-helper${SUFFIX}
cp bin/harvester-network-webhook${SUFFIX} dist/artifacts/harvester-network-webhook${SUFFIX}

CONTROLLER_IMAGE=${REPO}/harvester-network-controller:${TAG}
HELPER_IMAGE=${REPO}/harvester-network-helper:${TAG}
WEBHOOK_IMAGE=${REPO}/harvester-network-webhook:${TAG}
DOCKERFILE_CONTROLLER=package/Dockerfile
DOCKERFILE_HELPER=package/Dockerfile.helper
DOCKERFILE_WEBHOOK=package/Dockerfile.webhook
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

buildx build --load -f ${DOCKERFILE_CONTROLLER} -t ${CONTROLLER_IMAGE} .
echo Built ${CONTROLLER_IMAGE}

buildx build --load -f ${DOCKERFILE_HELPER} -t ${HELPER_IMAGE} .
echo Built ${HELPER_IMAGE}

buildx build --load -f ${DOCKERFILE_WEBHOOK} -t ${WEBHOOK_IMAGE} .
echo Built ${WEBHOOK_IMAGE}
