name: Dev Build and Publish

on:
  push:
    branches:
    - master
    - 'v1.*'

jobs:
  build-main:
    uses: ./.github/workflows/template-build.yml
    with:
      release-tag-name: ${{ github.ref_name }}-head
      push: true
    secrets: inherit
