on:
  workflow_call:
    inputs:
      refs:
        required: false
        type: string
      release-tag-name:
        required: true
        type: string
      push:
        required: true
        type: boolean

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  dapper-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: harvester-network-controller
            dockerfile: package/Dockerfile
          - image: harvester-network-helper
            dockerfile: package/Dockerfile.helper
          - image: harvester-network-webhook
            dockerfile: package/Dockerfile.webhook
    steps:
    - name: Checkout code without refs
      if: ${{ inputs.refs == '' }}
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Checkout code with refs
      if: ${{ inputs.refs != '' }}
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        ref: ${{ inputs.refs }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

    - name: Run dapper
      run: make ci

    - name: Resolve registries
      id: resolve
      uses: harvester/harvester-actions/actions/resolve-registries@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main
      with:
        release-tag-name: ${{ inputs.release-tag-name }}
        is-release: ${{ github.event_name == 'release' && github.event.action == 'published' }}

    - name: Set image tag
      run: echo "IMAGE_TAG=${RELEASE_TAG_NAME#prime-}" >> "$GITHUB_ENV"
      env:
        RELEASE_TAG_NAME: ${{ inputs.release-tag-name }}

    - name: Login to Docker Hub
      id: login-docker
      if: ${{ inputs.push == true && steps.resolve.outputs.use-docker-io == 'true' }}
      uses: harvester/harvester-actions/actions/login-docker-hub@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main

    - name: Publish public ${{ matrix.image }} image
      if: ${{ inputs.push == true && steps.resolve.outputs.use-docker-io == 'true' }}
      uses: harvester/harvester-actions/actions/publish-public-image@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main
      with:
        context: .
        dockerfile: ${{ matrix.dockerfile }}
        image: ${{ matrix.image }}
        tag: ${{ env.IMAGE_TAG }}
        platforms: ${{ env.PLATFORMS }}
        registry: ${{ steps.login-docker.outputs.registry }}
        repository: ${{ steps.login-docker.outputs.repository }}

    - name: Login to Staging Registry
      id: login-staging
      if: ${{ inputs.push == true && steps.resolve.outputs.use-staging == 'true' }}
      uses: harvester/harvester-actions/actions/login-staging-registry@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main

    - name: Publish staging ${{ matrix.image }} image
      if: ${{ inputs.push == true && steps.resolve.outputs.use-staging == 'true' }}
      uses: harvester/harvester-actions/actions/publish-prime-image@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main
      with:
        context: .
        dockerfile: ${{ matrix.dockerfile }}
        image: ${{ matrix.image }}
        tag: ${{ env.IMAGE_TAG }}
        platforms: ${{ env.PLATFORMS }}
        registry: ${{ steps.login-staging.outputs.registry }}
        repository: ${{ steps.login-staging.outputs.repository }}

    - name: Login to Prime Registry
      id: login-prime
      if: ${{ inputs.push == true && steps.resolve.outputs.use-prime == 'true' }}
      uses: harvester/harvester-actions/actions/login-prime-registry@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main

    - name: Publish prime ${{ matrix.image }} image
      if: ${{ inputs.push == true && steps.resolve.outputs.use-prime == 'true' }}
      uses: harvester/harvester-actions/actions/publish-prime-image@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main
      with:
        context: .
        dockerfile: ${{ matrix.dockerfile }}
        image: ${{ matrix.image }}
        tag: ${{ env.IMAGE_TAG }}
        platforms: ${{ env.PLATFORMS }}
        registry: ${{ steps.login-prime.outputs.registry }}
        repository: ${{ steps.login-prime.outputs.repository }}
